services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_refresh_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mercure
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test_db_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "find . -type d -name '__pycache__' -exec rm -rf {} + && pytest -v --disable-warnings --import-mode=importlib"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:mercure@db:5432/test_refresh_system
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONPATH: /app
      DEBUG: "1"
      TESTING: "1"

volumes:
  test_db_data:
